<a href="https://colab.research.google.com/github/KodumuruRaja/Feature-Engineering/blob/main/Feature-Engineering-(How%20Cardinality%20(Categorical-Encoding)%20Used%20to%20Improve%20Models).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split

In [ ]:
data=pd.read_csv("/content/titanic.csv")

In [ ]:
data.head()

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [ ]:
data.shape

(891, 12)

In [ ]:
#checking Cardinality(No of Unique Values) of columns
len(data['Name'].unique())

891

In [ ]:
len(data['Sex'].unique())

2

In [ ]:
len(data['Ticket'].unique())

681

In [ ]:
len(data['Cabin'].unique())

148

In [ ]:
data=data[['Cabin','Sex','Survived']]

In [ ]:
data

Cabin     Sex  Survived
0     NaN    male         0
1     C85  female         1
2     NaN  female         1
3    C123  female         1
4     NaN    male         0
..    ...     ...       ...
886   NaN    male         0
887   B42  female         1
888   NaN  female         0
889  C148    male         1
890   NaN    male         0

[891 rows x 3 columns]

In [ ]:
#To reduce Cardinality of Cabin
data['Cabin'].str[0]

0      NaN
1        C
2      NaN
3        C
4      NaN
      ... 
886    NaN
887      B
888    NaN
889      C
890    NaN
Name: Cabin, Length: 891, dtype: object

In [ ]:
data['Cabin'].str[0].unique()

array([nan, 'C', 'E', 'G', 'D', 'A', 'B', 'F', 'T'], dtype=object)

In [ ]:
data['Cabin'].str[0].fillna('n')

0      n
1      C
2      n
3      C
4      n
      ..
886    n
887    B
888    n
889    C
890    n
Name: Cabin, Length: 891, dtype: object

In [ ]:
data['Cabin'].str[0].fillna('n').unique()

array(['n', 'C', 'E', 'G', 'D', 'A', 'B', 'F', 'T'], dtype=object)

In [ ]:
data['Cabin_reduced']=data['Cabin'].str[0].fillna('n')

In [ ]:
data

Cabin     Sex  Survived Cabin_reduced
0     NaN    male         0             n
1     C85  female         1             C
2     NaN  female         1             n
3    C123  female         1             C
4     NaN    male         0             n
..    ...     ...       ...           ...
886   NaN    male         0             n
887   B42  female         1             B
888   NaN  female         0             n
889  C148    male         1             C
890   NaN    male         0             n

[891 rows x 4 columns]

In [ ]:
len(data['Cabin'].unique())

148

In [ ]:
len(data['Cabin_reduced'].unique())

9

In [ ]:
len(data['Sex'].unique())

2

# **Train Test Split**

In [ ]:
use_cols=['Cabin','Cabin_reduced','Sex']
x_train,x_test,y_train,y_test=train_test_split(data[use_cols],data['Survived'],test_size=0.40,random_state=0)

In [ ]:
x_train.shape,x_test.shape

((534, 3), (357, 3))

In [ ]:
tcu=x_test['Cabin'].unique()
tcu

array([nan, 'B78', 'C106', 'C125', 'C7', 'B49', 'C54', 'E34', 'C52',
       'B50', 'B41', 'C83', 'B57 B59 B63 B66', 'E67', 'D45', 'D10 D12',
       'C47', 'C87', 'D20', 'D17', 'B42', 'C126', 'C23 C25 C27', 'D9',
       'F33', 'C65', 'B102', 'F2', 'B18', 'D49', 'F G73', 'G6', 'E33',
       'B96 B98', 'C62 C64', 'B37', 'C78', 'B58 B60', 'C85', 'D36',
       'C124', 'B71', 'B30', 'A26', 'B69', 'E68', 'E121', 'C68', 'B94',
       'E17', 'D33', 'D26', 'C128', 'A14', 'B19', 'D21', 'C148', 'C30',
       'D56', 'E24', 'E40', 'E31', 'E44', 'E38', 'D37', 'E8', 'C92',
       'E63', 'F4'], dtype=object)

In [ ]:
tncu=x_train['Cabin'].unique()
tncu

array([nan, 'E67', 'C126', 'B73', 'E36', 'C78', 'E46', 'C111', 'E101',
       'D15', 'E12', 'G6', 'A32', 'B4', 'A10', 'A5', 'C95', 'E25', 'C90',
       'D6', 'A36', 'D', 'D26', 'D50', 'B96 B98', 'C93', 'E77', 'C101',
       'D11', 'C123', 'C32', 'B35', 'C91', 'T', 'B101', 'E58', 'A23',
       'B77', 'D28', 'B82 B84', 'B79', 'E44', 'C45', 'C2', 'B5', 'C104',
       'B20', 'A19', 'B51 B53 B55', 'B80', 'B38', 'B22', 'B18', 'C22 C26',
       'E8', 'A16', 'F2', 'D47', 'E121', 'D33', 'C23 C25 C27', 'B28',
       'E10', 'D36', 'C46', 'B39', 'D30', 'E33', 'C50', 'D20', 'C124',
       'A34', 'C110', 'D19', 'B86', 'D35', 'C99', 'D46', 'F38', 'A24',
       'D7', 'C65', 'C103', 'A31', 'C82', 'F G63', 'A6', 'E50', 'C68',
       'C52', 'B3', 'B49', 'C118', 'C70', 'F E69', 'F4', 'C86', 'D48',
       'C49', 'C92', 'A7', 'A20', 'E24', 'E49'], dtype=object)

In [ ]:
len(tncu)-len(tcu)

35

# **Cabin**

In [ ]:
[x for x in tncu if x not in tcu]

[nan,
 'B73',
 'E36',
 'E46',
 'C111',
 'E101',
 'D15',
 'E12',
 'A32',
 'B4',
 'A10',
 'A5',
 'C95',
 'E25',
 'C90',
 'D6',
 'A36',
 'D',
 'D50',
 'C93',
 'E77',
 'C101',
 'D11',
 'C123',
 'C32',
 'B35',
 'C91',
 'T',
 'B101',
 'E58',
 'A23',
 'B77',
 'D28',
 'B82 B84',
 'B79',
 'C45',
 'C2',
 'B5',
 'C104',
 'B20',
 'A19',
 'B51 B53 B55',
 'B80',
 'B38',
 'B22',
 'C22 C26',
 'A16',
 'D47',
 'B28',
 'E10',
 'C46',
 'B39',
 'D30',
 'C50',
 'A34',
 'C110',
 'D19',
 'B86',
 'D35',
 'C99',
 'D46',
 'F38',
 'A24',
 'D7',
 'C103',
 'A31',
 'C82',
 'F G63',
 'A6',
 'E50',
 'B3',
 'C118',
 'C70',
 'F E69',
 'C86',
 'D48',
 'C49',
 'A7',
 'A20',
 'E49']

In [ ]:
len([x for x in tncu if x not in tcu])

80

In [ ]:
[x for x in tcu if x not in tncu]

[nan,
 'B78',
 'C106',
 'C125',
 'C7',
 'C54',
 'E34',
 'B50',
 'B41',
 'C83',
 'B57 B59 B63 B66',
 'D45',
 'D10 D12',
 'C47',
 'C87',
 'D17',
 'B42',
 'D9',
 'F33',
 'B102',
 'D49',
 'F G73',
 'C62 C64',
 'B37',
 'B58 B60',
 'C85',
 'B71',
 'B30',
 'A26',
 'B69',
 'E68',
 'B94',
 'E17',
 'C128',
 'A14',
 'B19',
 'D21',
 'C148',
 'C30',
 'D56',
 'E40',
 'E31',
 'E38',
 'D37',
 'E63']

In [ ]:
len([x for x in tcu if x not in tncu])

45

# **Cabin Reduced**

In [ ]:
len([x for x in x_train['Cabin_reduced'].unique() if x not in x_test['Cabin_reduced'].unique()])

1

In [ ]:
len([x for x in x_test['Cabin_reduced'].unique() if x not in x_train['Cabin_reduced'].unique()])

0

# **Categorical Encoding**

In [ ]:
data

Cabin     Sex  Survived Cabin_reduced
0     NaN    male         0             n
1     C85  female         1             C
2     NaN  female         1             n
3    C123  female         1             C
4     NaN    male         0             n
..    ...     ...       ...           ...
886   NaN    male         0             n
887   B42  female         1             B
888   NaN  female         0             n
889  C148    male         1             C
890   NaN    male         0             n

[891 rows x 4 columns]

In [ ]:
x_train

Cabin Cabin_reduced     Sex
100   NaN             n  female
722   NaN             n    male
678   NaN             n  female
229   NaN             n  female
334   NaN             n  female
..    ...           ...     ...
835   E49             E  female
192   NaN             n  female
629   NaN             n    male
559   NaN             n  female
684   NaN             n    male

[534 rows x 3 columns]

In [ ]:
x_train.isnull().sum()

Cabin            407
Cabin_reduced      0
Sex                0
dtype: int64

In [ ]:
x_test.isnull().sum()

Cabin            280
Cabin_reduced      0
Sex                0
dtype: int64

In [ ]:
x_train.fillna(0,inplace=True)

In [ ]:
x_test.fillna(0,inplace=True)

In [ ]:
x_train.isnull().sum(),x_test.isnull().sum()

(Cabin            0
 Cabin_reduced    0
 Sex              0
 dtype: int64, Cabin            0
 Cabin_reduced    0
 Sex              0
 dtype: int64)

In [ ]:
x_train

Cabin Cabin_reduced     Sex
100     0             n  female
722     0             n    male
678     0             n  female
229     0             n  female
334     0             n  female
..    ...           ...     ...
835   E49             E  female
192     0             n  female
629     0             n    male
559     0             n  female
684     0             n    male

[534 rows x 3 columns]

In [ ]:
#['Cabin','Sex']
#['Cabin_reduced','Sex']

In [ ]:
pd.get_dummies(x_train,columns=['Cabin','Sex'])

Cabin_reduced  Cabin_0  Cabin_A10  ...  Cabin_T  Sex_female  Sex_male
100             n        1          0  ...        0           1         0
722             n        1          0  ...        0           0         1
678             n        1          0  ...        0           1         0
229             n        1          0  ...        0           1         0
334             n        1          0  ...        0           1         0
..            ...      ...        ...  ...      ...         ...       ...
835             E        0          0  ...        0           1         0
192             n        1          0  ...        0           1         0
629             n        1          0  ...        0           0         1
559             n        1          0  ...        0           1         0
684             n        1          0  ...        0           0         1

[534 rows x 107 columns]

In [ ]:
pd.get_dummies(x_test,columns=['Cabin','Sex'])

Cabin_reduced  Cabin_0  Cabin_A14  ...  Cabin_G6  Sex_female  Sex_male
495             n        1          0  ...         0           0         1
648             n        1          0  ...         0           0         1
278             n        1          0  ...         0           0         1
31              B        0          0  ...         0           1         0
255             n        1          0  ...         0           1         0
..            ...      ...        ...  ...       ...         ...       ...
363             n        1          0  ...         0           0         1
406             n        1          0  ...         0           0         1
866             n        1          0  ...         0           1         0
881             n        1          0  ...         0           0         1
618             F        0          0  ...         0           1         0

[357 rows x 72 columns]

In [ ]:
train=pd.get_dummies(x_train[['Cabin','Sex']],columns=['Cabin','Sex'])

In [ ]:
test=pd.get_dummies(x_test[['Cabin','Sex']],columns=['Cabin','Sex'])

In [ ]:
train.shape,test.shape

((534, 106), (357, 71))

# **Balance the columns of train and test**

In [ ]:
missing_cols=set(train.columns)-set(test.columns)

In [ ]:
missing_cols

{'Cabin_A10',
 'Cabin_A16',
 'Cabin_A19',
 'Cabin_A20',
 'Cabin_A23',
 'Cabin_A24',
 'Cabin_A31',
 'Cabin_A32',
 'Cabin_A34',
 'Cabin_A36',
 'Cabin_A5',
 'Cabin_A6',
 'Cabin_A7',
 'Cabin_B101',
 'Cabin_B20',
 'Cabin_B22',
 'Cabin_B28',
 'Cabin_B3',
 'Cabin_B35',
 'Cabin_B38',
 'Cabin_B39',
 'Cabin_B4',
 'Cabin_B5',
 'Cabin_B51 B53 B55',
 'Cabin_B73',
 'Cabin_B77',
 'Cabin_B79',
 'Cabin_B80',
 'Cabin_B82 B84',
 'Cabin_B86',
 'Cabin_C101',
 'Cabin_C103',
 'Cabin_C104',
 'Cabin_C110',
 'Cabin_C111',
 'Cabin_C118',
 'Cabin_C123',
 'Cabin_C2',
 'Cabin_C22 C26',
 'Cabin_C32',
 'Cabin_C45',
 'Cabin_C46',
 'Cabin_C49',
 'Cabin_C50',
 'Cabin_C70',
 'Cabin_C82',
 'Cabin_C86',
 'Cabin_C90',
 'Cabin_C91',
 'Cabin_C93',
 'Cabin_C95',
 'Cabin_C99',
 'Cabin_D',
 'Cabin_D11',
 'Cabin_D15',
 'Cabin_D19',
 'Cabin_D28',
 'Cabin_D30',
 'Cabin_D35',
 'Cabin_D46',
 'Cabin_D47',
 'Cabin_D48',
 'Cabin_D50',
 'Cabin_D6',
 'Cabin_D7',
 'Cabin_E10',
 'Cabin_E101',
 'Cabin_E12',
 'Cabin_E25',
 'Cabin_E36',
 'Cabi

In [ ]:
for c in missing_cols:
  test[c]=0

In [ ]:
test=test[train.columns]

In [ ]:
train.shape,test.shape

((534, 106), (357, 106))

In [ ]:
clf=RandomForestClassifier(n_estimators=200,random_state=42)
clf.fit(train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=200,
                       n_jobs=None, oob_score=False, random_state=42, verbose=0,
                       warm_start=False)

In [ ]:
y_train_pred=clf.predict_proba(train)
y_test_pred=clf.predict_proba(test)

In [ ]:
y_train_pred

array([[0.3296787 , 0.6703213 ],
       [0.86457227, 0.13542773],
       [0.3296787 , 0.6703213 ],
       ...,
       [0.86457227, 0.13542773],
       [0.3296787 , 0.6703213 ],
       [0.86457227, 0.13542773]])

In [ ]:
print('Train Set')
print('{} roc_auc:{}'.format('Random Forest',roc_auc_score(y_train,y_train_pred[:,1])))
print('Test Set')
print('{} roc_auc:{}'.format('Random Forest',roc_auc_score(y_test,y_test_pred[:,1])))

Train Set
Random Forest roc_auc:0.8729650130239166
Test Set
Random Forest roc_auc:0.8261744743146127


# **ML Models Building**

In [ ]:
def run_models(data_train,data_test,y_train,y_test):
  rf=RandomForestClassifier(n_estimators=200,random_state=42)
  ada=AdaBoostClassifier(n_estimators=200,random_state=42)
  logit=LogisticRegression(solver='lbfgs',random_state=42)
  gbc=GradientBoostingClassifier(n_estimators=300,random_state=42)
  models={
      'Random Forest':rf,
      'AdaBoost':ada,
      'Logistic Regression':logit,
      'Gradient Boost':gbc
  }
  # categorical encoding
  train=pd.get_dummies(data_train,columns=data_train.columns)
  test=pd.get_dummies(data_test,columns=data_test.columns)
  missing_cols=set(train.columns)-set(test.columns)
  for c in missing_cols:
    test[c]=0
  test=test[train.columns]
  for label,clf in models.items():
    clf.fit(train,y_train)
    y_train_pred=clf.predict_proba(train)
    y_test_pred=clf.predict_proba(test)
    print('Testing for{}',label)
    print('Train roc_auc:{}'.format(roc_auc_score(y_train,y_train_pred[:,1])))
    print('Test roc_auc:{}'.format(roc_auc_score(y_test,y_test_pred[:,1])))
    print()

In [ ]:
x_train.columns

Index(['Cabin', 'Cabin_reduced', 'Sex'], dtype='object')

In [ ]:
# High Cardinality
cols=['Cabin','Sex']
run_models(x_train[cols],x_test[cols],y_train,y_test)

Testing for{} Random Forest
Train roc_auc:0.8729650130239166
Test roc_auc:0.8261744743146127

Testing for{} AdaBoost
Train roc_auc:0.8699310324413924
Test roc_auc:0.7899254724514241

Testing for{} Logistic Regression
Train roc_auc:0.8328572697134738
Test roc_auc:0.819204152249135

Testing for{} Gradient Boost
Train roc_auc:0.8743858039308549
Test roc_auc:0.8247604471652914



In [ ]:
# Low cardinality
# High Cardinality
cols=['Cabin_reduced','Sex']
run_models(x_train[cols],x_test[cols],y_train,y_test)

Testing for{} Random Forest
Train roc_auc:0.8310812810798011
Test roc_auc:0.8101377428799574

Testing for{} AdaBoost
Train roc_auc:0.8283284986976084
Test roc_auc:0.8166589033803567

Testing for{} Logistic Regression
Train roc_auc:0.8274109045702107
Test roc_auc:0.8159602076124568

Testing for{} Gradient Boost
Train roc_auc:0.8310812810798011
Test roc_auc:0.8101377428799574

